import math
print(math.pi, math.e)
print()

print('тригонометрия')
print(math.sin(90))
print('упс')
print(math.sin(math.pi/2))
print(math.sin(math.radians(90)))
print(math.degrees(math.pi/4))
print(math.cos(math.radians(90)))
print('ой')
print(math.tan(math.radians(90)))
print(math.asin(0.5))
print(math.degrees(math.acos(0.5)))
print()

print('всякоразное:')
print(math.sqrt(625))
print(math.factorial(5))
print(math.exp(1))
print(math.log2(32))
print(math.log10(1000))
print(math.log(243, 3))
